languages:
   JavaScript: true
   PHP: true
exclude_paths:
 - src/assets/js/materialize.js
 - src/system/*
 - src/application/libraries/Markdown.php
 - src/application/third_party/*
 - src/application/libraries/Recaptcha.php
 - src/index.php
